config/routes.rb
AppBiropum::Application.routes.draw do
  resources :paintings


  resources :galleries


  resources :foto_galeris


  resources :importtodbs do
    get 'import_todb'
    get 'import_agama'
    get 'import_pekerjaan'
    get 'import_pendidikan'
    get 'import_statuskawin'
    get 'import_umur'
    get 'import_usiasekolah'
  end

  resources :db_jmlh_pddks
  resources :db_agamas
  resources :db_pekerjaans
  resources :db_pendidikans
  resources :db_statuskawins
  resources :db_umurs
  resources :db_usiasekolahs

  resources :posts do
    member do
      get :download
    end
  end

  get "home/kontakkami"

  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/db_agama.rb
class DbAgama < ActiveRecord::Base
  attr_accessible :desa_kel, :kd_kec, :kd_kel, :kdkab, :nama_kab, :nama_kec, :laki, :perempuan, :islam, :kristen, :katolik, :hindu, :budha, :konghucu, :kepercayaan, :jumlah_penduduk 
  
  def self.searchkec(a)
  	if a.present?
  		where('nama_kab LIKE ?', "%#{a}%")
  	else
  		scoped
  	end
  end

  def self.searchkeckel(a, b)
  	if a.present? && b.present?
  		where('nama_kec LIKE ? and desa_kel LIKE ?', "%#{a}%", "%#{b}%")
  	else
  		scoped
  	end
  end
end

app/controllers/db_agamas_controller.rb
class DbAgamasController < ApplicationController
  # GET /db_agamas
  # GET /db_agamas.json
  def index
    #@db_agamas = DbAgama.all
    if params[:search_kab].present?       
      @cbokab = DbAgama.select( :nama_kab ).uniq.order("nama_kab")
      @db_agamas = DbAgama.searchkec(params[:search_kab]) #.order("desa_kel")
      #@db_agamas = DbAgama.where( :nama_kec => params[:search_kab] )
    else
      @cbokab = DbAgama.select( :nama_kab ).uniq.order("nama_kab")
      @db_agamas = DbAgama.where('false')
    end
    #@db_agamas = DbAgama.search(params[:search_kab]).order("nama_kec")

    respond_to do |format|
      if params[:search_kab].present? 
        format.html { render :partial => 'result', :object => @db_agamas }
      else
        format.html
      end
      #format.json { render json: @db_agamas }
      #format.js
    end
  end

  # GET /db_agamas/1
  # GET /db_agamas/1.json
  def show
    @db_agama = DbAgama.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @db_agama }
    end
  end

  # GET /db_agamas/new
  # GET /db_agamas/new.json
  def new
    @db_agama = DbAgama.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @db_agama }
    end
  end

  # GET /db_agamas/1/edit
  def edit
    @db_agama = DbAgama.find(params[:id])
  end

  # POST /db_agamas
  # POST /db_agamas.json
  def create
    @db_agama = DbAgama.new(params[:db_agama])

    respond_to do |format|
      if @db_agama.save
        format.html { redirect_to @db_agama, notice: 'Db jmlh pddk was successfully created.' }
        format.json { render json: @db_agama, status: :created, location: @db_agama }
      else
        format.html { render action: "new" }
        format.json { render json: @db_agama.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /db_agamas/1
  # PUT /db_agamas/1.json
  def update
    @db_agama = DbAgama.find(params[:id])

    respond_to do |format|
      if @db_agama.update_attributes(params[:db_agama])
        format.html { redirect_to @db_agama, notice: 'Db jmlh pddk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @db_agama.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /db_agamas/1
  # DELETE /db_agamas/1.json
  def destroy
    @db_agama = DbAgama.find(params[:id])
    @db_agama.destroy

    respond_to do |format|
      format.html { redirect_to db_agamas_url }
      format.json { head :no_content }
    end
  end
end

app/views/db_agamas/_result.html.erb
<table class="back-for-table table table-bordered table-striped table-hover">
      <tr>
        <th>Kode Kabupaten</th>
        <th>Nama Kabupaten</th>
        <th>Kode Kecamatan</th>
        <th>Nama Kecamatan</th>
        <th>Kode Kelurahan</th>
        <th>Desa Kelurahan</th>
        <th>Laki</th>
        <th>Perempuan</th>
        <th>Islam</th>
        <th>Kristen</th>
        <th>Katolik </th>
        <th>Hindu </th>
        <th>Budha </th>
        <th>Konghucu </th>
        <th>Kepercayaan </th>
        <th>Jumlah Penduduk</th>
        <% if user_signed_in? %> 
          <th></th>
          <th></th>
          <th></th>
        <% end %>
      </tr>

    <% result.each do |db_agama| %>
      <tr>
        <td><%= db_agama.kdkab %></td>
        <td><%= db_agama.nama_kab %></td>
        <td><%= db_agama.kd_kec %></td>
        <td><%= db_agama.nama_kec %></td>
        <td><%= db_agama.kd_kel %></td>
        <td><%= db_agama.desa_kel %></td>
        <th><%= number_with_delimiter( db_agama.laki ) %></th>
        <th><%= number_with_delimiter( db_agama.perempuan ) %></th>
        <th><%= number_with_delimiter( db_agama.islam ) %></th>
        <th><%= number_with_delimiter( db_agama.kristen ) %></th>
        <th><%= number_with_delimiter( db_agama.katolik  ) %></th>
        <th><%= number_with_delimiter( db_agama.hindu  ) %></th>
        <th><%= number_with_delimiter( db_agama.budha  ) %></th>
        <th><%= number_with_delimiter( db_agama.konghucu  ) %></th>
        <th><%= number_with_delimiter( db_agama.kepercayaan  ) %></th>
        <th><%= number_with_delimiter( db_agama.jumlah_penduduk ) %></th>
        <% if user_signed_in? %> 
          <td><%= link_to 'Show', db_agama %></td>
          <td><%= link_to 'Edit', edit_db_agama_path(db_agama) %></td>
          <td><%= link_to 'Destroy', db_agama, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    </table>

app/views/db_agamas/index.html.erb
<div class="span11">  
  <h3>Informasi Kependudukan</h3>
  <div class="progress progress-info progress-striped"><div class="bar" style="width: 30%;"></div></div>
    <h3 class="small">Jumlah Penduduk berdasarkan Agama <%= params[ :search_kab ].nil? ? '' : 'Kabupaten ' + params[ :search_kab ] %></h3>

    <%= form_tag db_agamas_path, :method => 'get', :class => 'form-inline' do %>
        <div class="row">
            <div class="span6">
              Pilih Kabupaten : <%= select_tag 'search_kab', options_for_select(@cbokab.collect{ |u| [u.nama_kab, u.nama_kab] }), :prompt => "Pilih Kabupaten" %>&nbsp;<%= image_tag("/assets/ajax-loader.gif", :id => "loader") %></div>
        </div>
    <% end %>

    <div id="result_table">
      <%= render :partial => 'result', :object => @db_agamas %>    
    </div>

    <% if user_signed_in? %>  
      <br />
      <%= link_to 'New Db Agama', new_db_agama_path %>
    <% end %>
</div>

<script>
  $(document).ready(function(){
    $("#loader").hide();
    $('#search_kab').change(function() { 
      var hsl_item = $('#search_kab').val()
          ;
      if (hsl_item) {
        $.ajax({
            url: "/db_agamas",
            type: 'GET',
            data: { search_kab: hsl_item },
            //dataType: 'json',
            start: function () {
              $("#loader").show();
            },
            success: function (data) {
              //$('#hasil2_hsl_lab_satuan').val( data.labsatuan[0] );
              $("#result_table").html(data);
            },
            complete: function () {
              $("#loader").hide();
            },
            error: function (jqXHR, data) {         
              //$("#idpasien").append ( data );
            }
        });
      }
      //change txtInterest% value
      //$('#hasil2_hsl_lab_item_name').val(hsl_item);
      //$('#hasil2_hsl_lab_satuan').val(@lab2_item_selected);
    });

  });
</script>