config/routes.rb
AppBiropum::Application.routes.draw do
  resources :paintings


  resources :galleries


  resources :foto_galeris


  resources :importtodbs do
    get 'import_todb'
    get 'import_agama'
    get 'import_pekerjaan'
    get 'import_pendidikan'
    get 'import_statuskawin'
    get 'import_umur'
    get 'import_usiasekolah'
  end

  resources :db_jmlh_pddks
  resources :db_agamas
  resources :db_pekerjaans
  resources :db_pendidikans
  resources :db_statuskawins
  resources :db_umurs
  resources :db_usiasekolahs

  resources :posts do
    member do
      get :download
    end
  end

  get "home/kontakkami"

  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/db_pekerjaan.rb
class DbPekerjaan < ActiveRecord::Base
  attr_accessible :belum_tidak_bekerja, :desa_kel, :kd_kab, :kd_kec, :kd_kel, :laki, :mengurus_rumah_tangga, :nama_kab, :nama_kec, :pegawai_negeri_sipil, :pelajar_mahasiswa, :pensiunan, :perempuan, :tentara_nasional_indonesia, 	 :kepolisian_ri, :perdagangan, :petani_pekebun, :peternak, :nelayan_perikanan, :industri, :konstruksi, :transportasi, :karyawan_swasta, :karyawan_bumn, :karyawan_bumd, :karyawan_honorer, :buruh_harian_lepas, :buruh_tani_perkebunan, :buruh_nelayan_perikanan, :buruh_peternakan, :pembantu_rumah_tangga, :tukang_cukur, :tukang_lisrik, :tukang_batu, :tukang_kayu, :tukang_sol_sepatu, :tukang_las_pandai_besi, :tukang_jahit, :tukang_gigi, :penata_rias, :penata_busana, :penata_rambut, :mekanik, :seniman, :tabib, :paraji, :perancang_busana, :penterjemah, :imam_mesjid, :pendeta, :pastor, :wartawan, :ustadz_mubaligh, :juru_masak, :promotor_acara, :anggota_dpr_ri, :anggota_dpd, :anggota_bpk, :presiden, :wakil_presiden, :anggota_mahkamah_konstitusi, :anggota_kabinet_kementrian, :duta_besar, :gubernur, :wakil_gubernur, :bupati, :wakil_bupati, :walikota, :wakil_walikota, :anggota_dprd_provinsi, :anggota_dprd_kabupaten_kota, :dosen, :guru, :pilot, :pengacara, :notaris, :arsitek, :akuntan, :konsultan, :dokter, :bidan, :perawat, :apoteker, :psikiater_psikolog, :penyiar_televisi, :penyiar_radio, :pelaut, :peneliti, :sopir, :pialang, :paranormal, :pedagang, :perangkat_desa, :kepala_desa, :biarawati, :wiraswasta, :lainnya, :jumlah_penduduk

  def self.searchkec(a)
  	if a.present?
  		where('nama_kab LIKE ?', "%#{a}%")
  	else
  		scoped
  	end
  end

  def self.searchkeckel(a, b)
  	if a.present? && b.present?
  		where('nama_kec LIKE ? and desa_kel LIKE ?', "%#{a}%", "%#{b}%")
  	else
  		scoped
  	end
  end
end

app/controllers/db_pekerjaans_controller.rb
class DbPekerjaansController < ApplicationController
  # GET /db_pekerjaans
  # GET /db_pekerjaans.json
  def index
    #@db_pekerjaans = DbPekerjaan.all
    if params[:search_kab].present?       
      @cbokab = DbPekerjaan.select( :nama_kab ).uniq.order("nama_kab")
      @db_pekerjaans = DbPekerjaan.searchkec(params[:search_kab]) #.order("desa_kel")
      #@db_pekerjaans = DbPekerjaan.where( :nama_kec => params[:search_kab] )
    else
      @cbokab = DbPekerjaan.select( :nama_kab ).uniq.order("nama_kab")
      @db_pekerjaans = DbPekerjaan.where('false')
    end
    #@db_pekerjaans = DbPekerjaan.search(params[:search_kab]).order("nama_kec")

    respond_to do |format|
      if params[:search_kab].present? 
        format.html { render :partial => 'result', :object => @db_pekerjaans }
      else
        format.html
      end
      #format.json { render json: @db_pekerjaans }
      #format.js
    end
  end

  # GET /db_pekerjaans/1
  # GET /db_pekerjaans/1.json
  def show
    @db_pekerjaan = DbPekerjaan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @db_pekerjaan }
    end
  end

  # GET /db_pekerjaans/new
  # GET /db_pekerjaans/new.json
  def new
    @db_pekerjaan = DbPekerjaan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @db_pekerjaan }
    end
  end

  # GET /db_pekerjaans/1/edit
  def edit
    @db_pekerjaan = DbPekerjaan.find(params[:id])
  end

  # POST /db_pekerjaans
  # POST /db_pekerjaans.json
  def create
    @db_pekerjaan = DbPekerjaan.new(params[:db_pekerjaan])

    respond_to do |format|
      if @db_pekerjaan.save
        format.html { redirect_to @db_pekerjaan, notice: 'Db jmlh pddk was successfully created.' }
        format.json { render json: @db_pekerjaan, status: :created, location: @db_pekerjaan }
      else
        format.html { render action: "new" }
        format.json { render json: @db_pekerjaan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /db_pekerjaans/1
  # PUT /db_pekerjaans/1.json
  def update
    @db_pekerjaan = DbPekerjaan.find(params[:id])

    respond_to do |format|
      if @db_pekerjaan.update_attributes(params[:db_pekerjaan])
        format.html { redirect_to @db_pekerjaan, notice: 'Db jmlh pddk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @db_pekerjaan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /db_pekerjaans/1
  # DELETE /db_pekerjaans/1.json
  def destroy
    @db_pekerjaan = DbPekerjaan.find(params[:id])
    @db_pekerjaan.destroy

    respond_to do |format|
      format.html { redirect_to db_pekerjaans_url }
      format.json { head :no_content }
    end
  end
end

app/views/db_pekerjaans/_result.html.erb
<table class="back-for-table table table-bordered table-striped table-hover">
      <tr>
        <th>Kode Kabupaten</th>
        <th>Nama Kabupaten</th>
        <th>Kode Kecamatan</th>
        <th>Nama Kecamatan</th>
        <th>Kode Kelurahan</th>
        <th>Desa Kelurahan</th>
        <th>Laki</th>
        <th>Perempuan</th>
        <th>Belum/Tidak Bekerja</th>
        <th>Mengurus rumah tangga</th>
        <th>Pelajar/mahasiswa</th>
        <th>Pensiunan</th>
        <th>Pegawai Negeri Sipil</th>
        <th>Tentara Nasional Indonesia</th>
        <th>Kepolisian ri</th>
        <th>Perdagangan</th>
        <th>Petani/pekebun</th>
        <th>Peternak</th>
        <th>Nelayan/perikanan</th>
        <th>Industri</th>
        <th>Konstruksi</th>
        <th>Transportasi</th>
        <th>Karyawan Swasta</th>
        <th>Karyawan BUMN</th>
        <th>karyawan BUMD</th>
        <th>Karyawan Honorer</th>
        <th>Buruh harian lepas</th>
        <th>Buruh tani perkebunan</th>
        <th>Buruh nelayan perikanan</th>
        <th>Buruh peternakan</th>
        <th>Pembantu rumah tangga</th>
        <th>Tukang cukur</th>
        <th>Tukang lisrik</th>
        <th>Tukang batu</th>
        <th>Tukang kayu</th>
        <th>Tukang sol_sepatu</th>
        <th>Tukang las_pandai_besi</th>
        <th>Tukang jahit</th>
        <th>Tukang gigi</th>
        <th>Penata rias</th>
        <th>Penata busana</th>
        <th>Penata rambut</th>
        <th>Mekanik</th>
        <th>Seniman</th>
        <th>Tabib</th>
        <th>Paraji</th>
        <th>Perancang busana</th>
        <th>Penterjemah</th>
        <th>Imam_mesjid</th>
        <th>Pendeta</th>
        <th>Pastor</th>
        <th>Wartawan</th>
        <th>Ustadz/mubaligh</th>
        <th>Juru masak</th>
        <th>Promotor acara</th>
        <th>Anggota dpr ri</th>
        <th>Anggota dpd</th>
        <th>Anggota bpk</th>
        <th>Presiden</th>
        <th>Wakil presiden</th>
        <th>Anggota mahkamah konstitusi</th>
        <th>Anggota kabinet kementrian</th>
        <th>Duta besar</th>
        <th>Gubernur</th>
        <th>Wakil gubernur</th>
        <th>Bupati</th>
        <th>Wakil bupati</th>
        <th>Walikota</th>
        <th>Wakil walikota</th>
        <th>Anggota dprd provinsi</th>
        <th>Anggota dprd kabupaten/kota</th>
        <th>Dosen</th>
        <th>Guru</th>
        <th>Pilot</th>
        <th>Pengacara</th>
        <th>Notaris</th>
        <th>Arsitek</th>
        <th>Akuntan</th>
        <th>Konsultan</th>
        <th>Dokter</th>
        <th>Bidan</th>
        <th>Perawat</th>
        <th>Apoteker</th>
        <th>Psikiater/psikolog</th>
        <th>Penyiar televisi</th>
        <th>Penyiar radio</th>
        <th>Pelaut</th>
        <th>Peneliti</th>
        <th>Sopir</th>
        <th>Pialang</th>
        <th>Paranormal</th>
        <th>Pedagang</th>
        <th>Perangkat desa</th>
        <th>Kepala desa</th>
        <th>Biarawati</th>
        <th>Wiraswasta</th>
        <th>Lainnya</th>
        <th>Jumlah penduduk</th>

        <% if user_signed_in? %> 
          <th></th>
          <th></th>
          <th></th>
        <% end %>
      </tr>

    <% result.each do |db_pekerjaan| %>
      <tr>
        <td><%= db_pekerjaan.kd_kab %></td>
        <td><%= db_pekerjaan.nama_kab %></td>
        <td><%= db_pekerjaan.kd_kec %></td>
        <td><%= db_pekerjaan.nama_kec %></td>
        <td><%= db_pekerjaan.kd_kel %></td>
        <td><%= db_pekerjaan.desa_kel %></td>
        <th><%= number_with_delimiter( db_pekerjaan.laki ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.perempuan ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.belum_tidak_bekerja ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.mengurus_rumah_tangga ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.pelajar_mahasiswa ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.pensiunan ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.pegawai_negeri_sipil ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.tentara_nasional_indonesia ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.kepolisian_ri ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.perdagangan ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.petani_pekebun ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.peternak ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.nelayan_perikanan ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.industri ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.konstruksi ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.transportasi ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.karyawan_swasta ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.karyawan_bumn ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.karyawan_bumd ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.karyawan_honorer ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.buruh_harian_lepas ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.buruh_tani_perkebunan ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.buruh_nelayan_perikanan ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.buruh_peternakan ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.pembantu_rumah_tangga ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.tukang_cukur ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.tukang_lisrik ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.tukang_batu ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.tukang_kayu ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.tukang_sol_sepatu ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.tukang_las_pandai_besi ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.tukang_jahit ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.tukang_gigi ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.penata_rias ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.penata_busana ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.penata_rambut ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.mekanik ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.seniman ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.tabib ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.paraji ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.perancang_busana ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.penterjemah ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.imam_mesjid ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.pendeta ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.pastor ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.wartawan ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.ustadz_mubaligh ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.juru_masak ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.promotor_acara ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.anggota_dpr_ri ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.anggota_dpd ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.anggota_bpk ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.presiden ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.wakil_presiden ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.anggota_mahkamah_konstitusi ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.anggota_kabinet_kementrian ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.duta_besar ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.gubernur ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.wakil_gubernur ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.bupati ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.wakil_bupati ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.walikota ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.wakil_walikota ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.anggota_dprd_provinsi ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.anggota_dprd_kabupaten_kota ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.dosen ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.guru ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.pilot ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.pengacara ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.notaris ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.arsitek ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.akuntan ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.konsultan ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.dokter ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.bidan ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.perawat ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.apoteker ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.psikiater_psikolog ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.penyiar_televisi ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.penyiar_radio ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.pelaut ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.peneliti ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.sopir ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.pialang ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.paranormal ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.pedagang ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.perangkat_desa ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.kepala_desa ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.biarawati ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.wiraswasta ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.lainnya ) %></th>
        <th><%= number_with_delimiter( db_pekerjaan.jumlah_penduduk ) %></th>

        <% if user_signed_in? %> 
          <td><%= link_to 'Show', db_pekerjaan %></td>
          <td><%= link_to 'Edit', edit_db_pekerjaan_path(db_pekerjaan) %></td>
          <td><%= link_to 'Destroy', db_pekerjaan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    </table>

app/views/db_pekerjaans/index.html.erb
<div class="span11">  
  <h3>Informasi Kependudukan</h3>
  <div class="progress progress-info progress-striped"><div class="bar" style="width: 30%;"></div></div>
    <h3 class="small">Jumlah Penduduk berdasarkan Pekerjaan <%= params[ :search_kab ].nil? ? '' : 'Kabupaten ' + params[ :search_kab ] %></h3>

    <%= form_tag db_pekerjaans_path, :method => 'get', :class => 'form-inline' do %>
        <div class="row">
            <div class="span6">
              Pilih Kabupaten : <%= select_tag 'search_kab', options_for_select(@cbokab.collect{ |u| [u.nama_kab, u.nama_kab] }), :prompt => "Pilih Kabupaten" %>&nbsp;<%= image_tag("/assets/ajax-loader.gif", :id => "loader") %></div>
        </div>
    <% end %>

    <div id="result_table">
      <%= render :partial => 'result', :object => @db_pekerjaans %>    
    </div>

    <% if user_signed_in? %>  
      <br />
      <%= link_to 'New Db Pekerjaan', new_db_pekerjaan_path %>
    <% end %>
</div>

<script>
  $(document).ready(function(){
    $("#loader").hide();
    $('#search_kab').change(function() { 
      var hsl_item = $('#search_kab').val()
          ;
      if (hsl_item) {
        $.ajax({
            url: "/db_pekerjaans",
            type: 'GET',
            data: { search_kab: hsl_item },
            //dataType: 'json',
            start: function () {
              $("#loader").show();
            },
            success: function (data) {
              //$('#hasil2_hsl_lab_satuan').val( data.labsatuan[0] );
              $("#result_table").html(data);
            },
            complete: function () {
              $("#loader").hide();
            },
            error: function (jqXHR, data) {         
              //$("#idpasien").append ( data );
            }
        });
      }
      //change txtInterest% value
      //$('#hasil2_hsl_lab_item_name').val(hsl_item);
      //$('#hasil2_hsl_lab_satuan').val(@lab2_item_selected);
    });

  });
</script>