config/routes.rb
AppBiropum::Application.routes.draw do
  resources :paintings


  resources :galleries


  resources :foto_galeris


  resources :importtodbs do
    get 'import_todb'
    get 'import_agama'
    get 'import_pekerjaan'
    get 'import_pendidikan'
    get 'import_statuskawin'
    get 'import_umur'
    get 'import_usiasekolah'
  end

  resources :db_jmlh_pddks
  resources :db_agamas
  resources :db_pekerjaans
  resources :db_pendidikans
  resources :db_statuskawins
  resources :db_umurs
  resources :db_usiasekolahs

  resources :posts do
    member do
      get :download
    end
  end

  get "home/kontakkami"

  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/db_pendidikan.rb
class DbPendidikan < ActiveRecord::Base
  attr_accessible :belum_sekolah, :desa_kel, :dip_ii, :dip_iii, :jumlah_penduduk, :kd_kab, :kd_kec, :kd_kel, :laki, :nama_kab, :nama_kec, :perempuan, :slta, :sltp, :strata_i, :strata_ii, :strata_iii, :tamat_sd, :tidak_tamat_sd

  def self.searchkec(a)
  	if a.present?
  		where('nama_kab LIKE ?', "%#{a}%")
  	else
  		scoped
  	end
  end

  def self.searchkeckel(a, b)
  	if a.present? && b.present?
  		where('nama_kec LIKE ? and desa_kel LIKE ?', "%#{a}%", "%#{b}%")
  	else
  		scoped
  	end
  end
  
end

app/controllers/db_pendidikans_controller.rb
class DbPendidikansController < ApplicationController
  # GET /db_pendidikans
  # GET /db_pendidikans.json
  def index
    #@db_pendidikans = DbPendidikan.all
    if params[:search_kab].present?       
      @cbokab = DbPendidikan.select( :nama_kab ).uniq.order("nama_kab")
      @db_pendidikans = DbPendidikan.searchkec(params[:search_kab]) #.order("desa_kel")
      #@db_pendidikans = DbPendidikan.where( :nama_kec => params[:search_kab] )
    else
      @cbokab = DbPendidikan.select( :nama_kab ).uniq.order("nama_kab")
      @db_pendidikans = DbPendidikan.where('false')
    end
    #@db_pendidikans = DbPendidikan.search(params[:search_kab]).order("nama_kec")

    respond_to do |format|
      if params[:search_kab].present? 
        format.html { render :partial => 'result', :object => @db_pendidikans }
      else
        format.html
      end
      #format.json { render json: @db_pendidikans }
      #format.js
    end
  end

  # GET /db_pendidikans/1
  # GET /db_pendidikans/1.json
  def show
    @db_pendidikan = DbPendidikan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @db_pendidikan }
    end
  end

  # GET /db_pendidikans/new
  # GET /db_pendidikans/new.json
  def new
    @db_pendidikan = DbPendidikan.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @db_pendidikan }
    end
  end

  # GET /db_pendidikans/1/edit
  def edit
    @db_pendidikan = DbPendidikan.find(params[:id])
  end

  # POST /db_pendidikans
  # POST /db_pendidikans.json
  def create
    @db_pendidikan = DbPendidikan.new(params[:db_pendidikan])

    respond_to do |format|
      if @db_pendidikan.save
        format.html { redirect_to @db_pendidikan, notice: 'Db jmlh pddk was successfully created.' }
        format.json { render json: @db_pendidikan, status: :created, location: @db_pendidikan }
      else
        format.html { render action: "new" }
        format.json { render json: @db_pendidikan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /db_pendidikans/1
  # PUT /db_pendidikans/1.json
  def update
    @db_pendidikan = DbPendidikan.find(params[:id])

    respond_to do |format|
      if @db_pendidikan.update_attributes(params[:db_pendidikan])
        format.html { redirect_to @db_pendidikan, notice: 'Db jmlh pddk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @db_pendidikan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /db_pendidikans/1
  # DELETE /db_pendidikans/1.json
  def destroy
    @db_pendidikan = DbPendidikan.find(params[:id])
    @db_pendidikan.destroy

    respond_to do |format|
      format.html { redirect_to db_pendidikans_url }
      format.json { head :no_content }
    end
  end
end

app/views/db_pendidikans/_result.html.erb
<table class="back-for-table table table-bordered table-striped table-hover">
      <tr>
        <th>Kode Kabupaten</th>
        <th>Nama Kabupaten</th>
        <th>Kode Kecamatan</th>
        <th>Nama Kecamatan</th>
        <th>Kode Kelurahan</th>
        <th>Desa Kelurahan</th>
        <th>Laki</th>
        <th>Perempuan</th>
        <th>Belum Sekolah</th>
        <th>Tidak Tamat SD</th>
        <th>Tamat SD</th>
        <th>SLTP</th>
        <th>SLTA</th>
        <th>Diploma II</th>
        <th>Diploma III</th>
        <th>Strata I</th>
        <th>Strata II</th>
        <th>Strata III</th>
        <th>Jumlah Penduduk</th>
        <% if user_signed_in? %> 
          <th></th>
          <th></th>
          <th></th>
        <% end %>
      </tr>

    <% result.each do |db_pendidikan| %>
      <tr>
        <td><%= db_pendidikan.kd_kab %></td>
        <td><%= db_pendidikan.nama_kab %></td>
        <td><%= db_pendidikan.kd_kec %></td>
        <td><%= db_pendidikan.nama_kec %></td>
        <td><%= db_pendidikan.kd_kel %></td>
        <td><%= db_pendidikan.desa_kel %></td>
        <th><%= number_with_delimiter( db_pendidikan.laki ) %></th>
        <th><%= number_with_delimiter( db_pendidikan.perempuan ) %></th>
        <th><%= number_with_delimiter( db_pendidikan.belum_sekolah ) %></th>
        <th><%= number_with_delimiter( db_pendidikan.tidak_tamat_sd ) %></th>
        <th><%= number_with_delimiter( db_pendidikan.tamat_sd ) %></th>
        <th><%= number_with_delimiter( db_pendidikan.sltp ) %></th>
        <th><%= number_with_delimiter( db_pendidikan.slta ) %></th>
        <th><%= number_with_delimiter( db_pendidikan.dip_ii ) %></th>
        <th><%= number_with_delimiter( db_pendidikan.dip_iii ) %></th>
        <th><%= number_with_delimiter( db_pendidikan.strata_i ) %></th>
        <th><%= number_with_delimiter( db_pendidikan.strata_ii ) %></th>
        <th><%= number_with_delimiter( db_pendidikan.strata_iii ) %></th>
        <th><%= number_with_delimiter( db_pendidikan.jumlah_penduduk ) %></th>
        <% if user_signed_in? %> 
          <td><%= link_to 'Show', db_pendidikan %></td>
          <td><%= link_to 'Edit', edit_db_pendidikan_path(db_pendidikan) %></td>
          <td><%= link_to 'Destroy', db_pendidikan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    </table>

app/views/db_pendidikans/index.html.erb
<div class="span11">  
  <h3>Informasi Kependudukan</h3>
  <div class="progress progress-info progress-striped"><div class="bar" style="width: 30%;"></div></div>
    <h3 class="small">Jumlah Penduduk berdasarkan Pendidikan <%= params[ :search_kab ].nil? ? '' : 'Kabupaten ' + params[ :search_kab ] %></h3>

    <%= form_tag db_pendidikans_path, :method => 'get', :class => 'form-inline' do %>
        <div class="row">
            <div class="span6">
              Pilih Kabupaten : <%= select_tag 'search_kab', options_for_select(@cbokab.collect{ |u| [u.nama_kab, u.nama_kab] }), :prompt => "Pilih Kabupaten" %>&nbsp;<%= image_tag("/assets/ajax-loader.gif", :id => "loader") %></div>
        </div>
    <% end %>

    <div id="result_table">
      <%= render :partial => 'result', :object => @db_pendidikans %>    
    </div>

    <% if user_signed_in? %>  
      <br />
      <%= link_to 'New Db Pekerjaan', new_db_pendidikan_path %>
    <% end %>
</div>

<script>
  $(document).ready(function(){
    $("#loader").hide();
    $('#search_kab').change(function() { 
      var hsl_item = $('#search_kab').val()
          ;
      if (hsl_item) {
        $.ajax({
            url: "/db_pendidikans",
            type: 'GET',
            data: { search_kab: hsl_item },
            //dataType: 'json',
            start: function () {
              $("#loader").show();
            },
            success: function (data) {
              //$('#hasil2_hsl_lab_satuan').val( data.labsatuan[0] );
              $("#result_table").html(data);
            },
            complete: function () {
              $("#loader").hide();
            },
            error: function (jqXHR, data) {         
              //$("#idpasien").append ( data );
            }
        });
      }
      //change txtInterest% value
      //$('#hasil2_hsl_lab_item_name').val(hsl_item);
      //$('#hasil2_hsl_lab_satuan').val(@lab2_item_selected);
    });

  });
</script>