config/routes.rb
AppBiropum::Application.routes.draw do
  resources :paintings


  resources :galleries


  resources :foto_galeris


  resources :importtodbs do
    get 'import_todb'
    get 'import_agama'
    get 'import_pekerjaan'
    get 'import_pendidikan'
    get 'import_statuskawin'
    get 'import_umur'
    get 'import_usiasekolah'
  end

  resources :db_jmlh_pddks
  resources :db_agamas
  resources :db_pekerjaans
  resources :db_pendidikans
  resources :db_statuskawins
  resources :db_umurs
  resources :db_usiasekolahs

  resources :posts do
    member do
      get :download
    end
  end

  get "home/kontakkami"

  authenticated :user do
    root :to => 'home#index'
  end
  
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  
  friendly_id :title, use: :slugged
  attr_accessible :content, :dokumen, :image_url, :position, :title, :typepost
  mount_uploader :dokumen, DokumenUploader
  

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  def download
    @post = Post.find(params[:id])
    filepath = "#{Rails.root}/public" + @post.dokumen.to_s
    send_file filepath
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :position, :collection => ['Header 1', 'Header 2', 'Header 3', 'Left 1', 'Left 2', 'Left 3', 'Content 1', 'Content 2', 'Content 3', 'Footer 1', 'Footer 2', 'Footer 3'] %>
    <%= f.input :typepost %>
    <%= f.input :image_url %>
    <%= f.input :content, :input_html => { :class => 'ckeditor' } %>
    <%= f.input :dokumen, as: :file %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Position</th>
    <th>Typepost</th>
    <th>Image url</th>
    <th>Content</th>
    <th>Dokumen</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.position %></td>
    <td><%= post.typepost %></td>
    <td><%= post.image_url %></td>
    <td><%= post.content %></td>
    <td><%= post.dokumen %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<span class="span11">
  <h3><%= @post.title %></h3>
  <div class="progress progress-info progress-striped"><div class="bar" style="width: 30%;"></div></div>
  <%= sanitize(@post.content) %>
  <br />
  <% if @post.dokumen? %>
    <p>Untuk download, silahkan klik di bawah ini</p>
    <% if user_signed_in? %>
      <h3><%= link_to "Download " + @post.title, download_post_path(@post), :class => "btn btn-primary" %></h3>
    <% else %>    
      <h3><%= link_to @post.title, new_user_session_path, :class => "btn btn-primary" %></h3>
    <% end %>
  <% end %>  
</span>

app/views/posts/show1.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Position:</b>
  <%= @post.position %>
</p>

<p>
  <b>Typepost:</b>
  <%= @post.typepost %>
</p>

<p>
  <b>Image url:</b>
  <%= @post.image_url %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<p>
  <b>Dokumen:</b>
  <%= @post.dokumen %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>